/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package karyawanterbaik;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dani
 */
public class Karyawan extends javax.swing.JInternalFrame {

    /**
     * Creates new form Karyawan
     */
    public Karyawan() {
        initComponents();
        tampil();
        setTitle("Kelola Data Karyawan");
        jTextField1.requestFocus();
    }

    public Connection kon;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("NIP");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Alamat");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Jabatan");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Jenis kelamin");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Tanggal lahir");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("No. HP");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih -", "Perempuan", "Laki - Laki" }));

        jButton1.setText("Simpan");
        jButton1.setMaximumSize(new java.awt.Dimension(73, 28));
        jButton1.setMinimumSize(new java.awt.Dimension(73, 28));
        jButton1.setPreferredSize(new java.awt.Dimension(73, 28));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.setMaximumSize(new java.awt.Dimension(73, 28));
        jButton3.setMinimumSize(new java.awt.Dimension(73, 28));
        jButton3.setPreferredSize(new java.awt.Dimension(73, 28));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Keluar");
        jButton4.setMaximumSize(new java.awt.Dimension(73, 28));
        jButton4.setMinimumSize(new java.awt.Dimension(73, 28));
        jButton4.setPreferredSize(new java.awt.Dimension(73, 28));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIP", "Nama", "Alamat", "Jabatan", "Jenis kelamin", "Tanggal lahir", "No. HP"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jButton5.setText("Cari");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5))
                                    .addComponent(jTextField2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        simpan();
        reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "MAAF!!\nMasukan NIP yang akan di cari!");
            jTextField1.requestFocus();
        }else{
        cari();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void konek(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            kon = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbkp", "root", "");
        }catch(ClassNotFoundException cnfe){
            Logger.getLogger(Karyawan.class.getName()).log(Level.SEVERE, null, cnfe);
        } catch (SQLException se) {
            Logger.getLogger(Karyawan.class.getName()).log(Level.SEVERE, null, se);
        } catch (Exception e) {
            Logger.getLogger(Karyawan.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    public void simpan(){
        String fd = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(fd);
        String tgl = String.valueOf(fm.format(jXDatePicker1.getDate()));
        
        if (jTextField1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "MAAF!!\nNIP Tidak boleh kosong!");
        }else if (jTextField2.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "MAAF!!\nNama Tidak boleh kosong!");
        }else{
        try{
            konek();
            Statement st = kon.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM karyawan WHERE nip=\'"+jTextField1.getText()+"\';");
            if(rs.next()){
                st.executeUpdate("UPDATE karyawan SET nip=\'"+jTextField1.getText()+"\', nama=\'"+jTextField2.getText()+"\',"
                        + "alamat=\'"+jTextArea1.getText()+"\', jabatan=\'"+jTextField3.getText()+"\', jenis_kelamin=\'"+jComboBox1.getSelectedItem()+"\',"
                        + "tanggal_lahir=\'"+tgl+"\', no_hp=\'"+jTextField4.getText()+"\' WHERE nip=\'"+jTextField1.getText()+"\';");
                JOptionPane.showMessageDialog(this, "Perubahan Data Berhasil Disimpan");
                tampil();
            }else {
                String url = "INSERT INTO karyawan VALUES (\'"+jTextField1.getText()+"\',\'"+jTextField2.getText()+"\', \'"+jTextArea1.getText()+"\',"
                        + "\'"+jTextField3.getText()+"\',\'"+jComboBox1.getSelectedItem()+"\', \'"+tgl+"\', \'"+jTextField4.getText()+"\')";
                st.executeUpdate(url);
                JOptionPane.showMessageDialog(this, "Data Baru Telah Disimpan");
                tampil();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Periksa lagi database anda" + e);
            }
        }
    }
    
    public void hapus(){
        String fd = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(fd);
        String tgl = String.valueOf(fm.format(jXDatePicker1.getDate()));
        
        int respons = JOptionPane.showConfirmDialog(this,
            "Apakah anda yakin ingin menghapus data karyawan?\n",
        "Penghapusan Data",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE);

        if (respons == 0){
            try{
                konek();
                Statement st = kon.createStatement();
                st.executeUpdate("DELETE FROM karyawan WHERE nip=\'"+jTextField1.getText()+"\' AND nama=\'"+jTextField2.getText()+"\'"
                    + "AND alamat=\'"+jTextArea1.getText()+"\' AND jabatan=\'"+jTextField3.getText()+"\'"
                    + "AND Jenis_kelamin=\'"+jComboBox1.getSelectedItem()+"\' AND  tanggal_lahir=\'"+tgl+"\' AND no_hp=\'"+jTextField4.getText()+"\'");
                JOptionPane.showMessageDialog(rootPane, "Data Karyawan telah dihapus\n"
                        + "NIP :"+jTextField1.getText()+"\n"
                        + "Nama :"+jTextField2.getText()+"\n");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Data dalam database tidak ditemukan"+e);
            }
            reset();
            tampil();
        }else {
            reset();
        }  
    }
    
    public void cari(){
        try{
            konek();
            Statement st = kon.createStatement();
            ResultSet rs = st.executeQuery("SELECT karyawan.nip, karyawan.nama, karyawan.alamat, karyawan.jabatan,"
                    + "karyawan.jenis_kelamin, karyawan.tanggal_lahir, karyawan.no_hp FROM karyawan WHERE nip=\'"+jTextField1.getText()+"\'");
            rs.next();
            jTextField1.setText(rs.getString("karyawan.nip"));
            jTextField2.setText(rs.getString("karyawan.nama"));
            jTextArea1.setText(rs.getString("karyawan.alamat"));
            jTextField3.setText(rs.getString("karyawan.jabatan"));
            jComboBox1.setSelectedItem(rs.getString("karyawan.jenis_kelamin"));
            jXDatePicker1.setDate(rs.getDate("karyawan.tanggal_lahir"));
            jTextField4.setText(rs.getString("karyawan.no_hp"));
            rs.close();
            st.close();
            kon.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "NIP Tidak ada"+e);
        } 
    }
    
    public void tampil(){
        DefaultTableModel data = new DefaultTableModel();
        data.addColumn("NIP");
        data.addColumn("Nama");
        data.addColumn("Alamat");
        data.addColumn("Jabatan");
        data.addColumn("Jenis Kelamin");
        data.addColumn("Tanggal lahir");
        data.addColumn("No. HP");
        try{
            konek();
            String url = "SELECT * FROM karyawan ORDER BY `karyawan`.`nama` ASC;";
            Statement st = kon.createStatement();
            ResultSet rs = st.executeQuery(url);
            while (rs.next()) {
                data.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),
                rs.getString(5),rs.getString(6),rs.getString(7)});
            }
           jTable1.setModel(data);
        }catch (Exception e){
            
        }
    }
    
    public void reset(){
        jTextArea1.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jComboBox1.setSelectedIndex(0);
        jXDatePicker1.setDate(null);
        jTextField1.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables
}
