/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package karyawanterbaik;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dani
 */
public class Prestasi extends javax.swing.JInternalFrame {

    /**
     * Creates new form Prestasi
     */
    public Prestasi() {
        initComponents();
        tampil();
        setTitle("Kelola Data Prestasi");
        jTextField1.requestFocus();
    }
    
    public Connection kon;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtHasil = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtnama = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("NIP");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Absensi");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Sasaran kerja");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Target");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Realisasi");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Integritas");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Orientasi terhadap kualitas");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Kolaborasi");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Orientasi kepada customer");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Komunikasi");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Perencanaan dan pengorganisasian");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Perilaku menunjukan indikator yang diharapkan", "Perilaku menunjukan sebagian indikator yang diharapkan", "Perilaku menunjukan semua indikator yang diharapkan", "Perilaku melampaui semua indikator yang diharapkan", "Perilaku melampaui semua indikator yang diharapkan secara signifikan dan konsisten" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Tidak memenuhi (< 50% )", "Sebagian besar memenuhi ( 65% - 74% )", "Memenuhi ( 75% - 84% )", "Melampaui ( 85% - 94% )", "Sangat melampaui ( > 95% )" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Tidak memenuhi (< 50% )", "Sebagian besar memenuhi ( 65% - 74% )", "Memenuhi ( 75% - 84% )", "Melampaui ( 85% - 94% )", "Sangat melampaui ( > 95% )" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Tidak memenuhi (< 50% )", "Sebagian besar memenuhi ( 65% - 74% )", "Memenuhi ( 75% - 84% )", "Melampaui ( 85% - 94% )", "Sangat melampaui ( > 95% )" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Perilaku menunjukan indikator yang diharapkan", "Perilaku menunjukan sebagian indikator yang diharapkan", "Perilaku menunjukan semua indikator yang diharapkan", "Perilaku melampaui semua indikator yang diharapkan", "Perilaku melampaui semua indikator yang diharapkan secara signifikan dan konsisten" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Perilaku menunjukan indikator yang diharapkan", "Perilaku menunjukan sebagian indikator yang diharapkan", "Perilaku menunjukan semua indikator yang diharapkan", "Perilaku melampaui semua indikator yang diharapkan", "Perilaku melampaui semua indikator yang diharapkan secara signifikan dan konsisten" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Perilaku menunjukan indikator yang diharapkan", "Perilaku menunjukan sebagian indikator yang diharapkan", "Perilaku menunjukan semua indikator yang diharapkan", "Perilaku melampaui semua indikator yang diharapkan", "Perilaku melampaui semua indikator yang diharapkan secara signifikan dan konsisten" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Perilaku menunjukan indikator yang diharapkan", "Perilaku menunjukan sebagian indikator yang diharapkan", "Perilaku menunjukan semua indikator yang diharapkan", "Perilaku melampaui semua indikator yang diharapkan", "Perilaku melampaui semua indikator yang diharapkan secara signifikan dan konsisten" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Perilaku menunjukan indikator yang diharapkan", "Perilaku menunjukan sebagian indikator yang diharapkan", "Perilaku menunjukan semua indikator yang diharapkan", "Perilaku melampaui semua indikator yang diharapkan", "Perilaku melampaui semua indikator yang diharapkan secara signifikan dan konsisten" }));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Perilaku menunjukan indikator yang diharapkan", "Perilaku menunjukan sebagian indikator yang diharapkan", "Perilaku menunjukan semua indikator yang diharapkan", "Perilaku melampaui semua indikator yang diharapkan", "Perilaku melampaui semua indikator yang diharapkan secara signifikan dan konsisten" }));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });

        jButton1.setText("Simpan");
        jButton1.setPreferredSize(new java.awt.Dimension(73, 28));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");
        jButton2.setPreferredSize(new java.awt.Dimension(73, 28));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Keluar");
        jButton3.setPreferredSize(new java.awt.Dimension(73, 28));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("cari");
        jButton4.setPreferredSize(new java.awt.Dimension(60, 28));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Hasil");

        txtHasil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHasil.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel17.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel18.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel19.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel20.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel21.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel22.setPreferredSize(new java.awt.Dimension(50, 20));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Nama");

        txtnama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtnama.setPreferredSize(new java.awt.Dimension(42, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel23))
                    .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double C1 = jLabel13.getText().equals("") ? 0 : Double.parseDouble(jLabel13.getText());
        double C2 = jLabel14.getText().equals("") ? 0 : Double.parseDouble(jLabel14.getText());
        double C3 = jLabel15.getText().equals("") ? 0 : Double.parseDouble(jLabel15.getText());
        double C4 = jLabel16.getText().equals("") ? 0 : Double.parseDouble(jLabel16.getText());
        double C5 = jLabel17.getText().equals("") ? 0 : Double.parseDouble(jLabel17.getText());
        double C6 = jLabel18.getText().equals("") ? 0 : Double.parseDouble(jLabel18.getText());
        double C7 = jLabel19.getText().equals("") ? 0 : Double.parseDouble(jLabel19.getText());
        double C8 = jLabel20.getText().equals("") ? 0 : Double.parseDouble(jLabel20.getText());
        double C9 = jLabel21.getText().equals("") ? 0 : Double.parseDouble(jLabel21.getText());
        double C10 = jLabel22.getText().equals("") ? 0 : Double.parseDouble(jLabel22.getText());
        double tot = C1+C2+C3+C4+C5+C6+C7+C8+C9+C10;
        String hasil = String.format("%,.2f" , tot);
            txtHasil.setText(hasil);
        simpan();
        reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem() == "Perilaku menunjukan indikator yang diharapkan"){
            double A1 = 0.2; //persentase
            double B1 = 0.2; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel13.setText(E1);
        }else if(jComboBox1.getSelectedItem() == "Perilaku menunjukan sebagian indikator yang diharapkan"){
            double A1 = 0.2; //persentase
            double B1 = 0.4; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel13.setText(E1);
        }else if(jComboBox1.getSelectedItem() == "Perilaku menunjukan semua indikator yang diharapkan"){
            double A1 = 0.2; //persentase
            double B1 = 0.6; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel13.setText(E1);
        }else if(jComboBox1.getSelectedItem() == "Perilaku melampaui semua indikator yang diharapkan"){
            double A1 = 0.2; //persentase
            double B1 = 0.8; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel13.setText(E1);
        }else if(jComboBox1.getSelectedItem() == "Perilaku melampaui semua indikator yang diharapkan secara signifikan dan konsisten"){
            double A1 = 0.2; //persentase
            double B1 = 1; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel13.setText(E1);
        }else{
            jLabel13.setText("");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if(jComboBox2.getSelectedItem() == "Tidak memenuhi (< 50% )"){
            double A1 = 0.1; //persentase
            double B1 = 0.2; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel14.setText(E1);
        }else if(jComboBox2.getSelectedItem() == "Sebagian besar memenuhi ( 65% - 74% )"){
            double A1 = 0.1; //persentase
            double B1 = 0.4; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel14.setText(E1);
        }else if(jComboBox2.getSelectedItem() == "Memenuhi ( 75% - 84% )"){
            double A1 = 0.1; //persentase
            double B1 = 0.6; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel14.setText(E1);
        }else if(jComboBox2.getSelectedItem() == "Melampaui ( 85% - 94% )"){
            double A1 = 0.1; //persentase
            double B1 = 0.8; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel14.setText(E1);
        }else if(jComboBox2.getSelectedItem() == "Sangat melampaui ( > 95% )"){
            double A1 = 0.1; //persentase
            double B1 = 1; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel14.setText(E1);
        }else{
            jLabel14.setText("");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        if(jComboBox3.getSelectedItem() == "Tidak memenuhi (< 50% )"){
            double A1 = 0.1; //persentase
            double B1 = 1; //nilai MIN dibagi nilai bobot
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel15.setText(E1);
        }else if(jComboBox3.getSelectedItem() == "Sebagian besar memenuhi ( 65% - 74% )"){
            double A1 = 0.1; //persentase
            double B1 = 0.5; //nilai MIN dibagi nilai bobot
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel15.setText(E1);
        }else if(jComboBox3.getSelectedItem() == "Memenuhi ( 75% - 84% )"){
            double A1 = 0.1; //persentase
            double B1 = 0.33; //nilai MIN dibagi nilai bobot
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel15.setText(E1);
        }else if(jComboBox3.getSelectedItem() == "Melampaui ( 85% - 94% )"){
            double A1 = 0.1; //persentase
            double B1 = 0.25; //nilai MIN dibagi nilai bobot
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel15.setText(E1);
        }else if(jComboBox3.getSelectedItem() == "Sangat melampaui ( > 95% )"){
            double A1 = 0.1; //persentase
            double B1 = 0.2; //nilai MIN dibagi nilai bobot
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel15.setText(E1);
        }else{
            jLabel15.setText("");
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        if(jComboBox4.getSelectedItem() == "Tidak memenuhi (< 50% )"){
            double A1 = 0.05; //persentase
            double B1 = 1; //nilai MIN dibagi nilai bobot
            double D1 = B1*A1;
            String E1 = String.format("%,.3f" , D1);
            jLabel16.setText(E1);
        }else if(jComboBox4.getSelectedItem() == "Sebagian besar memenuhi ( 65% - 74% )"){
            double A1 = 0.05; //persentase
            double B1 = 0.5; //nilai MIN dibagi nilai bobot
            double D1 = B1*A1;
            String E1 = String.format("%,.3f" , D1);
            jLabel16.setText(E1);
        }else if(jComboBox4.getSelectedItem() == "Memenuhi ( 75% - 84% )"){
            double A1 = 0.05; //persentase
            double B1 = 0.33; //nilai MIN dibagi nilai bobot
            double D1 = B1*A1;
            String E1 = String.format("%,.3f" , D1);
            jLabel16.setText(E1);
        }else if(jComboBox4.getSelectedItem() == "Melampaui ( 85% - 94% )"){
            double A1 = 0.05; //persentase
            double B1 = 0.25; //nilai MIN dibagi nilai bobot
            double D1 = B1*A1;
            String E1 = String.format("%,.3f" , D1);
            jLabel16.setText(E1);
        }else if(jComboBox4.getSelectedItem() == "Sangat melampaui ( > 95% )"){
            double A1 = 0.05; //persentase
            double B1 = 0.2; //nilai MIN dibagi nilai bobot
            double D1 = B1*A1;
            String E1 = String.format("%,.3f" , D1);
            jLabel16.setText(E1);
        }else{
            jLabel16.setText("");
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        if(jComboBox5.getSelectedItem() == "Perilaku menunjukan indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.2; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel17.setText(E1);
        }else if(jComboBox5.getSelectedItem() == "Perilaku menunjukan sebagian indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.4; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel17.setText(E1);
        }else if(jComboBox5.getSelectedItem() == "Perilaku menunjukan semua indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.6; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel17.setText(E1);
        }else if(jComboBox5.getSelectedItem() == "Perilaku melampaui semua indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.8; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel17.setText(E1);
        }else if(jComboBox5.getSelectedItem() == "Perilaku melampaui semua indikator yang diharapkan secara signifikan dan konsisten"){
            double A1 = 0.1; //persentase
            double B1 = 1; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel17.setText(E1);
        }else{
            jLabel17.setText("");
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
        if(jComboBox6.getSelectedItem() == "Perilaku menunjukan indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.2; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel18.setText(E1);
        }else if(jComboBox6.getSelectedItem() == "Perilaku menunjukan sebagian indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.4; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel18.setText(E1);
        }else if(jComboBox6.getSelectedItem() == "Perilaku menunjukan semua indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.6; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel18.setText(E1);
        }else if(jComboBox6.getSelectedItem() == "Perilaku melampaui semua indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.8; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel18.setText(E1);
        }else if(jComboBox6.getSelectedItem() == "Perilaku melampaui semua indikator yang diharapkan secara signifikan dan konsisten"){
            double A1 = 0.1; //persentase
            double B1 = 1; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel18.setText(E1);
        }else{
            jLabel18.setText("");
        }
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
        if(jComboBox7.getSelectedItem() == "Perilaku menunjukan indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.2; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel19.setText(E1);
        }else if(jComboBox7.getSelectedItem() == "Perilaku menunjukan sebagian indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.4; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel19.setText(E1);
        }else if(jComboBox7.getSelectedItem() == "Perilaku menunjukan semua indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.6; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel19.setText(E1);
        }else if(jComboBox7.getSelectedItem() == "Perilaku melampaui semua indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.8; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel19.setText(E1);
        }else if(jComboBox7.getSelectedItem() == "Perilaku melampaui semua indikator yang diharapkan secara signifikan dan konsisten"){
            double A1 = 0.1; //persentase
            double B1 = 1; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel19.setText(E1);
        }else{
            jLabel19.setText("");
        }
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
        if(jComboBox8.getSelectedItem() == "Perilaku menunjukan indikator yang diharapkan"){
            double A1 = 0.05; //persentase
            double B1 = 1; //nilai MIN dibagi nilai bobot
            double D1 = B1*A1;
            String E1 = String.format("%,.3f" , D1);
            jLabel20.setText(E1);
        }else if(jComboBox8.getSelectedItem() == "Perilaku menunjukan sebagian indikator yang diharapkan"){
            double A1 = 0.05; //persentase
            double B1 = 0.5; //nilai MIN dibagi nilai bobot
            double D1 = B1*A1;
            String E1 = String.format("%,.3f" , D1);
            jLabel20.setText(E1);
        }else if(jComboBox8.getSelectedItem() == "Perilaku menunjukan semua indikator yang diharapkan"){
            double A1 = 0.05; //persentase
            double B1 = 0.33; //nilai MIN dibagi nilai bobot
            double D1 = B1*A1;
            String E1 = String.format("%,.3f" , D1);
            jLabel20.setText(E1);
        }else if(jComboBox8.getSelectedItem() == "Perilaku melampaui semua indikator yang diharapkan"){
            double A1 = 0.05; //persentase
            double B1 = 0.25; //nilai MIN dibagi nilai bobot
            double D1 = B1*A1;
            String E1 = String.format("%,.3f" , D1);
            jLabel20.setText(E1);
        }else if(jComboBox8.getSelectedItem() == "Perilaku melampaui semua indikator yang diharapkan secara signifikan dan konsisten"){
            double A1 = 0.05; //persentase
            double B1 = 0.2; //nilai MIN dibagi nilai bobot
            double D1 = B1*A1;
            String E1 = String.format("%,.3f" , D1);
            jLabel20.setText(E1);
        }else{
            jLabel20.setText("");
        }
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
        if(jComboBox9.getSelectedItem() == "Perilaku menunjukan indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.2; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel21.setText(E1);
        }else if(jComboBox9.getSelectedItem() == "Perilaku menunjukan sebagian indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.4; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel21.setText(E1);
        }else if(jComboBox9.getSelectedItem() == "Perilaku menunjukan semua indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.6; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel21.setText(E1);
        }else if(jComboBox9.getSelectedItem() == "Perilaku melampaui semua indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.8; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel21.setText(E1);
        }else if(jComboBox9.getSelectedItem() == "Perilaku melampaui semua indikator yang diharapkan secara signifikan dan konsisten"){
            double A1 = 0.1; //persentase
            double B1 = 1; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel21.setText(E1);
        }else{
            jLabel21.setText("");
        }
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
        if(jComboBox10.getSelectedItem() == "Perilaku menunjukan indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.2; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel22.setText(E1);
        }else if(jComboBox10.getSelectedItem() == "Perilaku menunjukan sebagian indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.4; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel22.setText(E1);
        }else if(jComboBox10.getSelectedItem() == "Perilaku menunjukan semua indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.6; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel22.setText(E1);
        }else if(jComboBox10.getSelectedItem() == "Perilaku melampaui semua indikator yang diharapkan"){
            double A1 = 0.1; //persentase
            double B1 = 0.8; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel22.setText(E1);
        }else if(jComboBox10.getSelectedItem() == "Perilaku melampaui semua indikator yang diharapkan secara signifikan dan konsisten"){
            double A1 = 0.1; //persentase
            double B1 = 1; //nilai bobot dibagi nilai MAX
            double D1 = B1*A1;
            String E1 = String.format("%,.2f" , D1);
            jLabel22.setText(E1);
        }else{
            jLabel22.setText("");
        }
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "MAAF!!\nMasukan NIP yang akan di cari!");
            jTextField1.requestFocus();
        }else{
        cari();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        carinama();
    }//GEN-LAST:event_jTextField1ActionPerformed

    public void konek(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            kon = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbkp", "root", "");
        }catch(ClassNotFoundException cnfe){
            Logger.getLogger(Karyawan.class.getName()).log(Level.SEVERE, null, cnfe);
        } catch (SQLException se) {
            Logger.getLogger(Karyawan.class.getName()).log(Level.SEVERE, null, se);
        } catch (Exception e) {
            Logger.getLogger(Karyawan.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    public void simpan(){
        if (jTextField1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "MAAF!!\nNIP Tidak boleh kosong!");
        }else if (jComboBox1.getSelectedItem() == "-Pilih-"){
            JOptionPane.showMessageDialog(this, "MAAF!!\nKriteria Absensi harus dipilih!");
        }else if (jComboBox2.getSelectedItem() == "-Pilih-"){
            JOptionPane.showMessageDialog(this, "MAAF!!\nKriteria Sasaran kerja harus dipilih!");
        }else if (jComboBox3.getSelectedItem() == "-Pilih-"){
            JOptionPane.showMessageDialog(this, "MAAF!!\nKriteria Target harus dipilih!");
        }else if (jComboBox4.getSelectedItem() == "-Pilih-"){
            JOptionPane.showMessageDialog(this, "MAAF!!\nKriteria Relasi harus dipilih!");
        }else if (jComboBox5.getSelectedItem() == "-Pilih-"){
            JOptionPane.showMessageDialog(this, "MAAF!!\nKriteria Integritas harus dipilih!");
        }else if (jComboBox6.getSelectedItem() == "-Pilih-"){
            JOptionPane.showMessageDialog(this, "MAAF!!\nKriteria Orientasi terhadap kualitas harus dipilih!");
        }else if (jComboBox7.getSelectedItem() == "-Pilih-"){
            JOptionPane.showMessageDialog(this, "MAAF!!\nKriteria kolaborasi harus dipilih!");
        }else if (jComboBox8.getSelectedItem() == "-Pilih-"){
            JOptionPane.showMessageDialog(this, "MAAF!!\nKriteria Orientasi terhadap customer harus dipilih!");
        }else if (jComboBox9.getSelectedItem() == "-Pilih-"){
            JOptionPane.showMessageDialog(this, "MAAF!!\nKriteria Komunikasi harus dipilih!");
        }else if (jComboBox1.getSelectedItem() == "-Pilih-"){
            JOptionPane.showMessageDialog(this, "MAAF!!\nKriteria Perencanaan dan pengorganisasian harus dipilih!");
        }else{
        try{
            konek();
            Statement st = kon.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM prestasi WHERE nip=\'"+jTextField1.getText()+"\';");
            if(rs.next()){
                st.executeUpdate("UPDATE prestasi SET nip=\'"+jTextField1.getText()+"\', nama=\'"+txtnama.getText()+"\', absensi=\'"+jComboBox1.getSelectedItem()+"\', sasaran_kerja=\'"+jComboBox2.getSelectedItem()+"\'"
                        + ", target=\'"+jComboBox3.getSelectedItem()+"\', realisasi=\'"+jComboBox4.getSelectedItem()+"\', integritas=\'"+jComboBox5.getSelectedItem()+"\', orientasi_terhadap_kualitas=\'"+jComboBox6.getSelectedItem()+"\'"
                        + ", kolaborasi=\'"+jComboBox7.getSelectedItem()+"\', orientasi_kepada_customer=\'"+jComboBox8.getSelectedItem()+"\', komunikasi=\'"+jComboBox9.getSelectedItem()+"\'"
                        + ", perencanaan_dan_pengorganisasian=\'"+jComboBox10.getSelectedItem()+"\', hasil=\'"+txtHasil.getText()+"\' WHERE nip=\'"+jTextField1.getText()+"\';");
                JOptionPane.showMessageDialog(this, "Perubahan Data Prestasi Berhasil Disimpan");
                tampil();
            }else {
                String url = "INSERT INTO prestasi (nip,nama,absensi,sasaran_kerja,target,realisasi,integritas,orientasi_terhadap_kualitas,kolaborasi,orientasi_kepada_customer,komunikasi,perencanaan_dan_pengorganisasian,hasil) "
                        + "VALUES (\'"+jTextField1.getText()+"\', \'"+txtnama.getText()+"\', \'"+jComboBox1.getSelectedItem()+"\', \'"+jComboBox2.getSelectedItem()+"\', \'"+jComboBox3.getSelectedItem()+"\', \'"+jComboBox4.getSelectedItem()+"\',"
                        + "\'"+jComboBox5.getSelectedItem()+"\', \'"+jComboBox6.getSelectedItem()+"\', \'"+jComboBox7.getSelectedItem()+"\', \'"+jComboBox8.getSelectedItem()+"\', \'"+jComboBox9.getSelectedItem()+"\',"
                        + "\'"+jComboBox10.getSelectedItem()+"\', \'"+txtHasil.getText()+"\')";
                st.executeUpdate(url);
                JOptionPane.showMessageDialog(this, "Data Prestasi Baru Telah Disimpan");
                tampil();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Periksa lagi database anda" + e);
            }
        }
    }
    
    public void hapus(){
        int respons = JOptionPane.showConfirmDialog(this,
            "Apakah anda yakin ingin menghapus data prestasi?\n",
        "Penghapusan Data",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE);

        if (respons == 0){
            try{
                konek();
                Statement st = kon.createStatement();
                st.executeUpdate("DELETE FROM prestasi WHERE nip=\'"+jTextField1.getText()+"\' AND nama=\'"+txtnama.getText()+"\' AND absensi=\'"+jComboBox1.getSelectedItem()+"\' "
                        + "AND  sasaran_kerja=\'"+jComboBox2.getSelectedItem()+"\' AND  target=\'"+jComboBox3.getSelectedItem()+"\' AND  realisasi=\'"+jComboBox4.getSelectedItem()+"\'"
                        + "AND  integritas=\'"+jComboBox5.getSelectedItem()+"\' AND  orientasi_terhadap_kualitas=\'"+jComboBox6.getSelectedItem()+"\' AND  kolaborasi=\'"+jComboBox7.getSelectedItem()+"\'"
                        + "AND  orientasi_kepada_customer=\'"+jComboBox8.getSelectedItem()+"\' AND  komunikasi=\'"+jComboBox9.getSelectedItem()+"\'"
                        + "AND  perencanaan_dan_pengorganisasian=\'"+jComboBox10.getSelectedItem()+"\' AND hasil=\'"+txtHasil.getText()+"\'");
                JOptionPane.showMessageDialog(rootPane, "Data Prestasi telah dihapus\n"
                        + "NIP :"+jTextField1.getText()+"\n"
                        + "Hasil :"+txtHasil.getText()+"\n");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Data dalam database tidak ditemukan"+e);
            }
            reset();
            tampil();
        }else {
            reset();
        }  
    }
    
    public void cari(){
        try{
            konek();
            Statement st = kon.createStatement();
            ResultSet rs = st.executeQuery("SELECT prestasi.nip, prestasi.nama, prestasi.absensi, prestasi.sasaran_kerja, prestasi.target,"
                    + "prestasi.realisasi, prestasi.integritas, prestasi.orientasi_terhadap_kualitas, prestasi.kolaborasi,"
                    + "prestasi.orientasi_kepada_customer, prestasi.komunikasi, prestasi.perencanaan_dan_pengorganisasian,"
                    + "prestasi.hasil FROM prestasi WHERE nip=\'"+jTextField1.getText()+"\'");
            rs.next();
            jTextField1.setText(rs.getString("prestasi.nip"));
            txtnama.setText(rs.getString("prestasi.nama"));
            jComboBox1.setSelectedItem(rs.getString("prestasi.absensi"));
            jComboBox2.setSelectedItem(rs.getString("prestasi.sasaran_kerja"));
            jComboBox3.setSelectedItem(rs.getString("prestasi.target"));
            jComboBox4.setSelectedItem(rs.getString("prestasi.realisasi"));
            jComboBox5.setSelectedItem(rs.getString("prestasi.integritas"));
            jComboBox6.setSelectedItem(rs.getString("prestasi.orientasi_terhadap_kualitas"));
            jComboBox7.setSelectedItem(rs.getString("prestasi.kolaborasi"));
            jComboBox8.setSelectedItem(rs.getString("prestasi.orientasi_kepada_customer"));
            jComboBox9.setSelectedItem(rs.getString("prestasi.komunikasi"));
            jComboBox10.setSelectedItem(rs.getString("prestasi.perencanaan_dan_pengorganisasian"));
            txtHasil.setText(rs.getString("prestasi.hasil"));
            rs.close();
            st.close();
            kon.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "NIP Tidak ada"+e);
        } 
    }
    
    public void carinama(){
        try{
            konek();
            Statement st = kon.createStatement();
            ResultSet rs = st.executeQuery("SELECT karyawan.nip, karyawan.nama FROM karyawan WHERE nip=\'"+jTextField1.getText()+"\'");
            rs.next();
            jTextField1.setText(rs.getString("karyawan.nip"));
            txtnama.setText(rs.getString("karyawan.nama"));
            rs.close();
            st.close();
            kon.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Data dengan NIP ini belom ada"+e);
        } 
    }
    
    public void tampil(){
        DefaultTableModel data = new DefaultTableModel();
        data.addColumn("NIP");
        data.addColumn("Nama");
        data.addColumn("Absensi");
        data.addColumn("Sasaran kerja");
        data.addColumn("Target");
        data.addColumn("Realisasi");
        data.addColumn("Integritas");
        data.addColumn("Orientasi terhadap kualitas");
        data.addColumn("Kolaborasi");
        data.addColumn("Orientasi kepada customer");
        data.addColumn("Komunikasi");
        data.addColumn("Perencanaan dan pengorganisasian");
        data.addColumn("Hasil");
        try{
            konek();
            String url = "SELECT * FROM prestasi ORDER BY `prestasi`.`nama` ASC;";
            Statement st = kon.createStatement();
            ResultSet rs = st.executeQuery(url);
            while (rs.next()) {
                data.addRow(new Object[]{rs.getString(2),rs.getString(3),rs.getString(4),
                rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),
                rs.getString(11),rs.getString(12),rs.getString(13),rs.getString(14)});
            }
           jTable1.setModel(data);
        }catch (Exception e){
            
        }
    }
    
    public void reset(){
        jTextField1.setText("");
        txtnama.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        jComboBox6.setSelectedIndex(0);
        jComboBox7.setSelectedIndex(0);
        jComboBox8.setSelectedIndex(0);
        jComboBox9.setSelectedIndex(0);
        jComboBox10.setSelectedIndex(0);
        txtHasil.setText("");
        jLabel14.setText("");
        jLabel15.setText("");
        jLabel16.setText("");
        jLabel17.setText("");
        jLabel18.setText("");
        jLabel19.setText("");
        jLabel20.setText("");
        jLabel21.setText("");
        jLabel22.setText("");
        jLabel13.setText("");
        jTextField1.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel txtHasil;
    private javax.swing.JLabel txtnama;
    // End of variables declaration//GEN-END:variables
}
